### PR TITLE
Search

### PR DESCRIPTION
**Pull request by PeterBell**
Adding search field - do you think this is enough?

### CODE REVIEW

**Comment by PeterBell** [comment]
@roninlabs-teacher would you mind checking this out?

**Comment by PeterBell** [comment]
We need at search box or it won't work

**Comment by PeterBell** [comment]
OK @roninlabs-teacher I think I've done it! Are we :+1: to :shipit: ?

**Comment by roninlabs-teacher** [comment]
Sure - I'm :+1: - 
harry-potter-congrats

**Pull request merged**
