### PR TITLE
Create about.html

### PR DESCRIPTION
**Pull request by roninlabs-teacher**

### CODE REVIEW

**Comment by roninlabs-teacher** [comment]
Hey @peterbell what do you think?

**Comment by PeterBell** [comment]
It should at least include a phone number

**Comment by PeterBell** [comment]
Give me 2 mins - I'll fix it

**Comment by roninlabs-teacher** [comment]
Looks good - gonna ship it :+1:?

**Comment by PeterBell** [comment]
YEah - :+1:

**Pull request merged**
